import pandas as pd
from tqdm import tqdm

# Create a Class to handle the Radiografia data
class Radiografia():
    def __init__(self):
        self.set_rad_variables()
    
    def set_rad_variables(self, inicio='', termino='', nombre=''):
        self.inicio = inicio
        self.termino = termino
        self.nombre = nombre
        self.__get_fechas_campana()

    def __get_fechas_campana(self):
        # Crear diccionario de fechas
        self.dict_fechas = {}

        if self.inicio and self.termino:
            # Obtener las fechas de inicio y fin un año antes
            self.inicio_a = (pd.to_datetime(self.inicio) - pd.DateOffset(years=1)).strftime('%Y-%m-%d')
            self.termino_a = (pd.to_datetime(self.termino) - pd.DateOffset(years=1)).strftime('%Y-%m-%d')
        
    def get_query_create_rad_tables(self, id, proveedores, nombre):
        query_rad_desc = f"""
            DROP TABLE IF EXISTS #MON_RAD_DESC;
            CREATE TABLE #MON_RAD_DESC (
                ID_RADIOGRAFIA TEXT
                ,NOMBRE TEXT
                ,PROVEEDOR TEXT
                ,VIGENCIA_INI DATE
                ,VIGENCIA_FIN DATE
            );

            INSERT INTO #MON_RAD_DESC VALUES
            ('{id}' ,'{nombre}', '{proveedores}', '{self.inicio}', '{self.termino}');

            DELETE CHEDRAUI.MON_RAD_DESC WHERE ID_RADIOGRAFIA = '{id}';
            INSERT INTO CHEDRAUI.MON_RAD_DESC SELECT * FROM #MON_RAD_DESC;
        """

        query_vta = f"""
            -- 1. TABLA DE VENTAS
            DROP TABLE IF EXISTS CHEDRAUI.VTA;
            CREATE TABLE CHEDRAUI.VTA AS (
            SELECT
                1::INT AS IND_MC
                ,LEFT(A.INVOICE_DATE, 7) MES
                ,A.PRODUCT_CODE
                ,A.INVOICE_NO
            --     ,A.INVOICE_DATE
                ,A.CUSTOMER_CODE_TY AS CUSTOMER_CODE

                ,B.CLASS_DESC
                ,B.SUBCLASS_DESC
                ,B.PROD_TYPE_DESC
                ,B.PRODUCT_DESCRIPTION
            --     ,B.PRODUCT_BRAND_VALUE
            --     ,B.PROD_ATTRIB15

                ,B.IND_MARCA
                ,B.PROVEEDOR
                ,B.MARCA
                ,B.IND_DUPLICADO
                
                ,CASE
                WHEN INVOICE_DATE BETWEEN '{self.inicio}' AND '{self.termino}' THEN 'ACTUAL'
                WHEN INVOICE_DATE BETWEEN '{self.inicio_a}' AND '{self.termino_a}' THEN 'ANO_ANTERIOR'
                END PERIODO

                ,COALESCE(C.NSE, 'NO SEGMENTADO') NSE
                ,COALESCE(C.TIPO_FAMILIA, 'NO SEGMENTADO') TIPO_FAMILIA
            --     ,COALESCE(C.CONTACT_INFO, 'NO SEGMENTADO') CONTACT_INFO
            --     ,COALESCE(C.VALID_CONTACT_INFO, 'NO SEGMENTADO') VALID_CONTACT_INFO

                ,D.REGION
                ,D.FORMATO_TIENDA

            --     ,E.FORMATO_TIENDA FORMATO_TIENDA_FAV
            --     ,E.STORE_DESCRIPTION DESCRIPCION_TIENDA_FAV
                
                ,F.IND_ONLINE
                            
                ,SUM(A.SALE_NET_VAL) AS VENTA
                ,SUM(A.SALE_TOT_QTY) AS UNIDADES
                    
            --     ,A.SALE_TOT_DISC_VAL COSTO

            FROM FCT_SALE_LINE A
            INNER JOIN #PRODUCTOS B USING(PRODUCT_CODE)
            LEFT JOIN CHEDRAUI.V_CUSTOMER_CONTACT AS C ON A.CUSTOMER_CODE_TY = C.CUSTOMER_CODE AND C.CONTACT_INFO IS NOT NULL
            LEFT JOIN CHEDRAUI.V_STORE D ON A.STORE_CODE = D.STORE_CODE AND A.STORE_KEY = D.STORE_KEY -- STORE OF THE CURRENT SALE
            --   LEFT JOIN CHEDRAUI.V_STORE E ON C.STORE_CODE = E.STORE_CODE AND C.STORE_KEY = E.STORE_KEY -- FAVORITE STORE OF CUSTOMER
            LEFT JOIN (SELECT DISTINCT INVOICE_NO, CASE WHEN CHANNEL_TYPE IN ('WEB','APP','CC HY') THEN 1 ELSE 0 END IND_ONLINE FROM FCT_SALE_HEADER) F USING(INVOICE_NO)
            WHERE (A.SALE_NET_VAL > 0 AND A.BUSINESS_TYPE = 'R')
            AND INVOICE_DATE BETWEEN '{self.inicio_a}' AND '{self.termino}'
            GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
            
            UNION ALL
            
            SELECT
                0::INT AS IND_MC
                ,LEFT(A.INVOICE_DATE, 7) MES
                ,A.PRODUCT_CODE
                ,A.INVOICE_NO
            --     ,A.INVOICE_DATE
                ,NULL CUSTOMER_CODE

                ,B.CLASS_DESC
                ,B.SUBCLASS_DESC
                ,B.PROD_TYPE_DESC
                ,B.PRODUCT_DESCRIPTION
            --     ,B.PRODUCT_BRAND_VALUE
            --     ,B.PROD_ATTRIB15
                
                ,B.IND_MARCA
                ,B.PROVEEDOR
                ,B.MARCA
                ,B.IND_DUPLICADO
                
                ,CASE
                WHEN INVOICE_DATE BETWEEN '{self.inicio}' AND '{self.termino}' THEN 'ACTUAL'
                WHEN INVOICE_DATE BETWEEN '{self.inicio_a}' AND '{self.termino_a}' THEN 'ANO_ANTERIOR'
                END PERIODO

                ,NULL NSE
                ,NULL TIPO_FAMILIA
            --     ,NULL CONTACT_INFO
            --     ,NULL VALID_CONTACT_INFO

                ,D.REGION
                ,D.FORMATO_TIENDA

            --     ,NULL FORMATO_TIENDA_FAV
            --     ,NULL DESCRIPCION_TIENDA_FAV
                
                ,F.IND_ONLINE
                            
                ,SUM(A.SALE_NET_VAL) AS VENTA
                ,SUM(A.SALE_TOT_QTY) AS UNIDADES
                    
            --     ,A.SALE_TOT_DISC_VAL COSTO

            FROM FCT_SALE_LINE_NM A
            INNER JOIN #PRODUCTOS B USING(PRODUCT_CODE)
            LEFT JOIN CHEDRAUI.V_STORE D ON A.STORE_CODE = D.STORE_CODE AND A.STORE_KEY = D.STORE_KEY -- STORE OF THE CURRENT SALE
            LEFT JOIN (SELECT DISTINCT INVOICE_NO, CASE WHEN CHANNEL_TYPE IN ('WEB','APP','CC HY') THEN 1 ELSE 0 END IND_ONLINE FROM FCT_SALE_HEADER_NM) F USING(INVOICE_NO)
            WHERE (A.SALE_NET_VAL > 0 AND A.BUSINESS_TYPE = 'R')
            AND INVOICE_DATE BETWEEN '{self.inicio_a}' AND '{self.termino}'
            GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
            );
            """
            
        query_rad_productos = f"""
            -- 2. PRODUCTOS MARCA Y CATEGORIA
            DROP TABLE IF EXISTS #MON_RAD_PRODUCTOS;
            CREATE TABLE #MON_RAD_PRODUCTOS AS (
            SELECT
                '{id}' ID_RADIOGRAFIA
                ,CLASS_CODE
                ,CLASS_DESC
                ,SUBCLASS_CODE
                ,SUBCLASS_DESC
                ,PROD_TYPE_DESC
                ,PRODUCT_CODE
                ,PRODUCT_BRAND_VALUE
                ,PROD_ATTRIB15
                ,COMMERCIALB_DESC
                ,PRODUCT_DESCRIPTION
                ,IND_MARCA
                ,MARCA
                ,PROVEEDOR
            FROM #PRODUCTOS
            );
            DELETE CHEDRAUI.MON_RAD_PRODUCTOS WHERE ID_RADIOGRAFIA ='{id}';
            INSERT INTO CHEDRAUI.MON_RAD_PRODUCTOS SELECT * FROM #MON_RAD_PRODUCTOS;
        """

        query_rad_cat = f"""
            -- 3. DATOS CATEGORIA ACTUAL Y AÑO ANTERIOR
            --TOTAL
            DROP TABLE IF EXISTS #MON_RAD_CAT_TOTAL;
            CREATE TABLE #MON_RAD_CAT_TOTAL AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,'TOTAL' CLASS_DESC
                ,'TOTAL' SUBCLASS_DESC
                ,'TOTAL' PROD_TYPE_DESC
                
                --ACTUAL
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE
                
                --AÑO ANTERIOR
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4
            );

            --CLASS
            DROP TABLE IF EXISTS #MON_RAD_CAT_CLASS;
            CREATE TABLE #MON_RAD_CAT_CLASS AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,CLASS_DESC
                ,'TOTAL' SUBCLASS_DESC
                ,'TOTAL' PROD_TYPE_DESC
                
                --ACTUAL
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE
                
                --AÑO ANTERIOR
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4
            );

            --SUBCLASS
            DROP TABLE IF EXISTS #MON_RAD_CAT_SUBCLASS;
            CREATE TABLE #MON_RAD_CAT_SUBCLASS AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,CLASS_DESC
                ,SUBCLASS_DESC
                ,'TOTAL' PROD_TYPE_DESC
                
                --ACTUAL
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE
                
                --AÑO ANTERIOR
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4
            );

            --PROD_TYPE_DESC
            DROP TABLE IF EXISTS #MON_RAD_CAT_PROD_TYPE_DESC;
            CREATE TABLE #MON_RAD_CAT_PROD_TYPE_DESC AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,CLASS_DESC
                ,SUBCLASS_DESC
                ,PROD_TYPE_DESC
                
                --ACTUAL
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE
                
                --AÑO ANTERIOR
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MARCA=1 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_DUPLICADO = 0 AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4
            );

            DROP TABLE IF EXISTS #MON_RAD_CAT;
            CREATE TABLE #MON_RAD_CAT AS (
            SELECT * FROM #MON_RAD_CAT_TOTAL
            UNION
            SELECT * FROM #MON_RAD_CAT_CLASS
            UNION
            SELECT * FROM #MON_RAD_CAT_SUBCLASS
            UNION
            SELECT * FROM #MON_RAD_CAT_PROD_TYPE_DESC
            ORDER BY 1,2,3,4
            );

            DROP TABLE IF EXISTS #MON_RAD_CAT_TOTAL;
            DROP TABLE IF EXISTS #MON_RAD_CAT_CLASS;
            DROP TABLE IF EXISTS #MON_RAD_CAT_SUBCLASS;
            DROP TABLE IF EXISTS #MON_RAD_CAT_PROD_TYPE_DESC;

            DELETE CHEDRAUI.MON_RAD_CAT WHERE ID_RADIOGRAFIA='{id}';
            INSERT INTO CHEDRAUI.MON_RAD_CAT SELECT * FROM #MON_RAD_CAT;
        """

        query_rad_datos_producto = f"""
        -- 4. DATOS PRODUCTO
            DROP TABLE IF EXISTS #MON_RAD_PRODUCTO;
            CREATE TABLE #MON_RAD_PRODUCTO AS (
            SELECT
                '{id}' ID_RADIOGRAFIA
                ,CLASS_DESC
                ,SUBCLASS_DESC
                ,PROD_TYPE_DESC
                ,MARCA
                ,PRODUCT_CODE
                ,PRODUCT_DESCRIPTION

                --ACTUAL
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE

                --ANTERIOR
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            WHERE IND_MARCA = 1
            GROUP BY 1,2,3,4,5,6,7
            HAVING VENTA_MARCA > 0
            );

            DELETE  CHEDRAUI.MON_RAD_PRODUCTO WHERE ID_RADIOGRAFIA='{id}';
            INSERT INTO CHEDRAUI.MON_RAD_PRODUCTO SELECT * FROM #MON_RAD_PRODUCTO ;
        """

        query_rad_marca = f"""
        -- 5. DATOS MARCA
            --AGG
            DROP TABLE IF EXISTS #MON_RAD_MARCA_AGG;
            CREATE TABLE #MON_RAD_MARCA_AGG AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,'TODAS' CLASS_DESC
                ,'TODAS' SUBCLASS_DESC
                ,'TODAS' PROD_TYPE_DESC
                ,MARCA
                
                --ACTUAL
                --MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                --CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE

                --AÑO ANTERIOR
                --MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                
                --CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4,5
            );

            --TOTAL
            DROP TABLE IF EXISTS #MON_RAD_MARCA_TOTAL;
            CREATE TABLE #MON_RAD_MARCA_TOTAL AS (
            SELECT 
                '{id}' ID_RADIOGRAFIA
                ,'TODAS' CLASS_DESC
                ,'TODAS' SUBCLASS_DESC
                ,'TODAS' PROD_TYPE_DESC
                ,'TOTAL' MARCA
                
                --ACTUAL
                --MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' THEN UNIDADES END) UNIDADES_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ACTUAL' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE
                --CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN VENTA END) VENTA_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' THEN INVOICE_NO END) TX_CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' THEN UNIDADES END) UNIDADES_CAT
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE
                ,SUM(CASE WHEN PERIODO = 'ACTUAL' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE

                --AÑO ANTERIOR
                --MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN VENTA END) VENTA_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN VENTA END) VENTA_MARCA_MC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN VENTA END) VENTA_MARCA_NMC_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN INVOICE_NO END) TX_MARCA_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN INVOICE_NO END) TX_MARCA_MC_AA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN INVOICE_NO END) TX_MARCA_NMC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' THEN UNIDADES END) UNIDADES_MARCA_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN UNIDADES END) UNIDADES_MARCA_MC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN UNIDADES END) UNIDADES_MARCA_NMC_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_ONLINE_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_MC_ONLINE_AA
                ,SUM(CASE WHEN IND_MARCA = 1 AND PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_MARCA_NMC_ONLINE_AA
                
                --CAT
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN CUSTOMER_CODE END) CLIENTES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN VENTA END) VENTA_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN VENTA END) VENTA_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN VENTA END) VENTA_CAT_NMC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN INVOICE_NO END) TX_CAT_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN INVOICE_NO END) TX_CAT_MC_AA
                ,COUNT(DISTINCT CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN INVOICE_NO END) TX_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' THEN UNIDADES END) UNIDADES_CAT_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 THEN UNIDADES END) UNIDADES_CAT_MC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 THEN UNIDADES END) UNIDADES_CAT_NMC_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=1 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_MC_ONLINE_AA
                ,SUM(CASE WHEN PERIODO = 'ANO_ANTERIOR' AND IND_MC=0 AND IND_ONLINE=1 THEN VENTA END) VENTA_CAT_NMC_ONLINE_AA
            FROM CHEDRAUI.VTA
            GROUP BY 1,2,3,4,5
            );

            DROP TABLE IF EXISTS #MON_RAD_MARCA;
            CREATE TABLE #MON_RAD_MARCA AS (
            SELECT * FROM #MON_RAD_MARCA_AGG
            UNION
            SELECT * FROM #MON_RAD_MARCA_TOTAL
            );

            DROP TABLE IF EXISTS #MON_RAD_MARCA_AGG;
            DROP TABLE IF EXISTS #MON_RAD_MARCA_TOTAL;
            
            DELETE CHEDRAUI.MON_RAD_MARCA  WHERE ID_RADIOGRAFIA='{id}';
            INSERT INTO CHEDRAUI.MON_RAD_MARCA SELECT * FROM #MON_RAD_MARCA;
        """

        query_rad_funnel_clientes = f"""
            -- 6. NUMERO DE COMPRAS
            --NUMERO DE COMPRAS
            DROP TABLE IF EXISTS #NUM_COMPRAS;
            CREATE TABLE #NUM_COMPRAS AS (
            WITH
            --MARCA
            __COMPRAS_POR_CLIENTE_MARCA AS (
                SELECT
                'MARCA' TIPO
                ,MARCA
                ,CUSTOMER_CODE
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 0 THEN INVOICE_NO END) TX_COMPETENCIA
                ,SUM(CASE WHEN IND_MARCA = 1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN IND_MARCA = 0 THEN VENTA END) VENTA_COMPETENCIA
                FROM CHEDRAUI.VTA
                WHERE IND_MC = 1
                AND PERIODO = 'ACTUAL'
                GROUP BY 1,2,3
            )
            ,__COMPRAS_POR_CLIENTE_MARCA_TOTAL AS (
            SELECT
                'MARCA' TIPO
                ,'TOTAL' MARCA
                ,CUSTOMER_CODE
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 0 THEN INVOICE_NO END) TX_COMPETENCIA
                ,SUM(CASE WHEN IND_MARCA = 1 THEN VENTA END) VENTA_MARCA
                ,SUM(CASE WHEN IND_MARCA = 0 THEN VENTA END) VENTA_COMPETENCIA
                FROM CHEDRAUI.VTA
                WHERE IND_MC = 1
                AND PERIODO = 'ACTUAL'
                GROUP BY 1,2,3
            )
            ,__COMPRAS_POR_CLIENTE_CAT AS (
                SELECT
                'CAT' TIPO
                ,'CAT' MARCA
                ,CUSTOMER_CODE
                ,COUNT(DISTINCT INVOICE_NO) TX_MARCA
                ,0::INT TX_COMPETENCIA
                ,SUM(VENTA) VENTA_MARCA
                ,0::INT VENTA_COMPETENCIA
                FROM CHEDRAUI.VTA
                WHERE IND_MC = 1
                AND PERIODO = 'ACTUAL'
                GROUP BY 1,2,3
            )
            ,__NUM_COMPRAS AS (
                SELECT
                TIPO
                ,MARCA
                --CLIENTES
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES_CAT
                ,COUNT(DISTINCT CASE WHEN TX_MARCA >= 1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,COUNT(DISTINCT CASE WHEN TX_MARCA = 1 THEN CUSTOMER_CODE END) CLIENTES_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA > 1 THEN CUSTOMER_CODE END) CLIENTES_MAS_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA = 1 AND TX_COMPETENCIA = 0 THEN CUSTOMER_CODE END) CLIENTES_SOLO_MARCA_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA > 1 AND TX_COMPETENCIA = 0 THEN CUSTOMER_CODE END) CLIENTES_SOLO_MARCA_MAS_UNA_VEZ
                --VENTA  
                ,SUM(VENTA_MARCA + VENTA_COMPETENCIA) VENTA_CAT
                ,SUM(CASE WHEN TX_MARCA >= 1 THEN VENTA_MARCA END) VENTA_MARCA
                ,SUM(CASE WHEN TX_MARCA = 1 THEN VENTA_MARCA END) VENTA_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA > 1 THEN VENTA_MARCA END) VENTA_MAS_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA = 1 AND TX_COMPETENCIA = 0 THEN VENTA_MARCA END) VENTA_SOLO_MARCA_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA > 1 AND TX_COMPETENCIA = 0 THEN VENTA_MARCA END) VENTA_SOLO_MARCA_MAS_UNA_VEZ

                FROM __COMPRAS_POR_CLIENTE_MARCA
                GROUP BY 1,2
                
                UNION
                
                SELECT
                TIPO
                ,MARCA
                --CLIENTES
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES_CAT
                ,COUNT(DISTINCT CASE WHEN TX_MARCA >= 1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,COUNT(DISTINCT CASE WHEN TX_MARCA = 1 THEN CUSTOMER_CODE END) CLIENTES_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA > 1 THEN CUSTOMER_CODE END) CLIENTES_MAS_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA = 1 AND TX_COMPETENCIA = 0 THEN CUSTOMER_CODE END) CLIENTES_SOLO_MARCA_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA > 1 AND TX_COMPETENCIA = 0 THEN CUSTOMER_CODE END) CLIENTES_SOLO_MARCA_MAS_UNA_VEZ
                --VENTA  
                ,SUM(VENTA_MARCA + VENTA_COMPETENCIA) VENTA_CAT
                ,SUM(CASE WHEN TX_MARCA >= 1 THEN VENTA_MARCA END) VENTA_MARCA
                ,SUM(CASE WHEN TX_MARCA = 1 THEN VENTA_MARCA END) VENTA_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA > 1 THEN VENTA_MARCA END) VENTA_MAS_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA = 1 AND TX_COMPETENCIA = 0 THEN VENTA_MARCA END) VENTA_SOLO_MARCA_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA > 1 AND TX_COMPETENCIA = 0 THEN VENTA_MARCA END) VENTA_SOLO_MARCA_MAS_UNA_VEZ
            
                FROM __COMPRAS_POR_CLIENTE_MARCA_TOTAL
                GROUP BY 1,2
                
                UNION
                
                SELECT
                TIPO
                ,MARCA
                --CLIENTES
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES_CAT
                ,COUNT(DISTINCT CASE WHEN TX_MARCA >= 1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,COUNT(DISTINCT CASE WHEN TX_MARCA = 1 THEN CUSTOMER_CODE END) CLIENTES_UNA_VEZ
                ,COUNT(DISTINCT CASE WHEN TX_MARCA > 1 THEN CUSTOMER_CODE END) CLIENTES_MAS_UNA_VEZ
                ,NULL CLIENTES_SOLO_MARCA_UNA_VEZ
                ,NULL CLIENTES_SOLO_MARCA_MAS_UNA_VEZ
                --VENTA  
                ,SUM(VENTA_MARCA + VENTA_COMPETENCIA) VENTA_CAT
                ,SUM(CASE WHEN TX_MARCA >= 1 THEN VENTA_MARCA END) VENTA_MARCA
                ,SUM(CASE WHEN TX_MARCA = 1 THEN VENTA_MARCA END) VENTA_UNA_VEZ
                ,SUM(CASE WHEN TX_MARCA > 1 THEN VENTA_MARCA END) VENTA_MAS_UNA_VEZ
                ,NULL VENTA_SOLO_MARCA_UNA_VEZ
                ,NULL VENTA_SOLO_MARCA_MAS_UNA_VEZ
            
                FROM __COMPRAS_POR_CLIENTE_CAT
                GROUP BY 1,2
            )

            SELECT * FROM __NUM_COMPRAS
            );

            --DORMIDOS Y PERDIDOS
            DROP TABLE IF EXISTS #DORMIDOS_PERDIDOS;
            CREATE TABLE #DORMIDOS_PERDIDOS AS (
            WITH
                __CLIENTES_MARCA AS (
                SELECT
                MARCA
                ,CUSTOMER_CODE

                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_D1]' AND '$[FEC_FIN_D1]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_D1
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_D2]' AND '$[FEC_FIN_D2]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_D2
                ,MAX(CASE WHEN (MES BETWEEN '$[FEC_INI_D2]' AND '$[FEC_FIN_D2]' OR MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]') AND IND_MARCA = 0 THEN 1 ELSE 0 END) IND_COMPETENCIA_D2

                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P1]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_P1
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_P2
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]' AND IND_MARCA = 0 THEN 1 ELSE 0 END) IND_COMPETENCIA_P2
                
                ,SUM(CASE WHEN MES BETWEEN '$[FEC_INI_D1]' AND '$[FEC_FIN_D2]' AND IND_MARCA=1 THEN VENTA ELSE 0 END) AS VENTA_DORMIDOS
                ,SUM(CASE WHEN MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P2]' AND IND_MARCA=1 THEN VENTA ELSE 0 END) AS VENTA_PERDIDOS
                
                FROM CHEDRAUI.VTA
                WHERE MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P2]'
                AND IND_MC = 1
                GROUP BY 1,2
            )
            ,__CLIENTES_MARCA_TOTAL AS (
                SELECT
                'TOTAL' MARCA
                ,CUSTOMER_CODE

                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_D1]' AND '$[FEC_FIN_D1]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_D1
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_D2]' AND '$[FEC_FIN_D2]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_D2
                ,MAX(CASE WHEN (MES BETWEEN '$[FEC_INI_D2]' AND '$[FEC_FIN_D2]' OR MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]') AND IND_MARCA = 0 THEN 1 ELSE 0 END) IND_COMPETENCIA_D2

                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P1]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_P1
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]' AND IND_MARCA = 1 THEN 1 ELSE 0 END) IND_MARCA_P2
                ,MAX(CASE WHEN MES BETWEEN '$[FEC_INI_P2]' AND '$[FEC_FIN_P2]' AND IND_MARCA = 0 THEN 1 ELSE 0 END) IND_COMPETENCIA_P2
                
                ,SUM(CASE WHEN MES BETWEEN '$[FEC_INI_D1]' AND '$[FEC_FIN_D2]' AND IND_MARCA=1 THEN VENTA ELSE 0 END) AS VENTA_DORMIDOS
                ,SUM(CASE WHEN MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P2]' AND IND_MARCA=1 THEN VENTA ELSE 0 END) AS VENTA_PERDIDOS
                
                FROM CHEDRAUI.VTA
                WHERE MES BETWEEN '$[FEC_INI_P1]' AND '$[FEC_FIN_P2]'
                AND IND_MC = 1
                GROUP BY 1,2
            )
            ,__DORMIDOS_PERDIDOS AS (
                -- SELECT TOP 10 * FROM __CLIENTES;
                SELECT
                MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA_D1 = 1 AND IND_MARCA_D2 = 0 AND IND_COMPETENCIA_D2 = 1 THEN CUSTOMER_CODE END) DORMIDOS
                ,COUNT(DISTINCT CASE WHEN IND_MARCA_P1 = 1 AND IND_MARCA_P2 = 0 AND IND_COMPETENCIA_P2 = 1 THEN CUSTOMER_CODE END) PERDIDOS
                ,SUM(CASE WHEN IND_MARCA_D1 = 1 AND IND_MARCA_D2 = 0 AND IND_COMPETENCIA_D2 = 1 THEN VENTA_DORMIDOS END) VENTA_DORMIDOS
                ,SUM(CASE WHEN IND_MARCA_P1 = 1 AND IND_MARCA_P2 = 0 AND IND_COMPETENCIA_P2 = 1 THEN VENTA_PERDIDOS END) VENTA_PERDIDOS
                FROM __CLIENTES_MARCA
                GROUP BY 1
            
                UNION
            
                SELECT
                MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA_D1 = 1 AND IND_MARCA_D2 = 0 AND IND_COMPETENCIA_D2 = 1 THEN CUSTOMER_CODE END) DORMIDOS
                ,COUNT(DISTINCT CASE WHEN IND_MARCA_P1 = 1 AND IND_MARCA_P2 = 0 AND IND_COMPETENCIA_P2 = 1 THEN CUSTOMER_CODE END) PERDIDOS
                ,SUM(CASE WHEN IND_MARCA_D1 = 1 AND IND_MARCA_D2 = 0 AND IND_COMPETENCIA_D2 = 1 THEN VENTA_DORMIDOS END) VENTA_DORMIDOS
                ,SUM(CASE WHEN IND_MARCA_P1 = 1 AND IND_MARCA_P2 = 0 AND IND_COMPETENCIA_P2 = 1 THEN VENTA_PERDIDOS END) VENTA_PERDIDOS
                FROM __CLIENTES_MARCA_TOTAL
                GROUP BY 1
            )
            SELECT
                *
            FROM __DORMIDOS_PERDIDOS
            );

            --10.DATOS COMPRAS
            DROP TABLE IF EXISTS #MON_RAD_FUNNEL_CLIENTES;
            CREATE TABLE #MON_RAD_FUNNEL_CLIENTES AS (
            SELECT
                '{id}' ID_RADIOGRAFIA
                ,TIPO
                ,A.MARCA
                --CLIENTES
                ,CLIENTES_CAT
                ,CLIENTES_MARCA
                ,CLIENTES_UNA_VEZ
                ,CLIENTES_MAS_UNA_VEZ
                ,CLIENTES_SOLO_MARCA_UNA_VEZ
                ,CLIENTES_SOLO_MARCA_MAS_UNA_VEZ
                ,DORMIDOS
                ,PERDIDOS
                --VENTA  
                ,VENTA_CAT
                ,VENTA_MARCA
                ,VENTA_UNA_VEZ
                ,VENTA_MAS_UNA_VEZ
                ,VENTA_SOLO_MARCA_UNA_VEZ
                ,VENTA_SOLO_MARCA_MAS_UNA_VEZ
                ,VENTA_DORMIDOS
                ,VENTA_PERDIDOS
            FROM #NUM_COMPRAS A
            LEFT JOIN #DORMIDOS_PERDIDOS B ON A.MARCA = B.MARCA AND A.TIPO = 'MARCA'
            ORDER BY 1,3 DESC
            );

            DELETE CHEDRAUI.MON_RAD_FUNNEL_CLIENTES WHERE ID_RADIOGRAFIA = '$[ID_RADIOGRAFIA]';
            INSERT INTO CHEDRAUI.MON_RAD_FUNNEL_CLIENTES SELECT * FROM #MON_RAD_FUNNEL_CLIENTES;
        """

        query_rad_evolucion = f"""
            -- 7. EVOLUCIÓN MARCA
            DROP TABLE IF EXISTS #MON_RAD_EVO;
            CREATE TABLE #MON_RAD_EVO AS (
            SELECT
                '{id}' ID_RADIOGRAFIA
                ,MES
                ,MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 THEN CUSTOMER_CODE END) CLIENTES_MARCA
                ,SUM(CASE WHEN IND_MARCA = 1 THEN VENTA END) VENTA_MARCA
                ,COUNT(DISTINCT CASE WHEN IND_MARCA = 1 THEN INVOICE_NO END) TX_MARCA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES_CAT
                ,SUM(VENTA) VENTA_CAT
                ,COUNT(DISTINCT INVOICE_NO) TX_CAT
            FROM CHEDRAUI.VTA 
            WHERE IND_MC = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3
            );

            DELETE CHEDRAUI.MON_RAD_EVO WHERE ID_RADIOGRAFIA='{id}';
            INSERT INTO CHEDRAUI.MON_RAD_EVO SELECT * FROM #MON_RAD_EVO;
        """

        query_rad_segmentado = f"""
            -- 8. SEGMENTADO
            DROP TABLE IF EXISTS #MON_RAD_SEGMENTADO;
            CREATE TABLE #MON_RAD_SEGMENTADO AS (
            WITH __SEGMENTADO AS (
            --NSE Y FAMILIA
                --MARCA
            SELECT
                'NSE_FAMILIA' TABLA
                ,MARCA
                ,NSE
                ,TIPO_FAMILIA
                ,'TOTAL' REGION
                ,'TOTAL' FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6

            UNION
            
                --TOTAL MARCA
            SELECT
                'NSE_FAMILIA' TABLA
                ,'{proveedores}' MARCA --AUNQUE MARCA ES GLOBAL, NO OCUPAMOS IND_DUPLICADO YA QUE SE CUENTAN DISTINCTOS CLIENTES, NO SE DUPLICAN. SOLO VENTA SE DUPLICARÍA.
                ,NSE
                ,TIPO_FAMILIA
                ,'TOTAL' REGION
                ,'TOTAL' FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6
            
            UNION
            
            --REGION
                --MARCA
            SELECT
                'REGION' TABLA
                ,MARCA
                ,'TOTAL' NSE
                ,'TOTAL' TIPO_FAMILIA
                ,REGION
                ,'TOTAL' FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6
            
            UNION
            
                --TOTAL MARCA
            SELECT
                'REGION' TABLA
                ,'{proveedores}' MARCA --AUNQUE MARCA ES GLOBAL, NO OCUPAMOS IND_DUPLICADO YA QUE SE CUENTAN DISTINCTOS CLIENTES, NO SE DUPLICAN. SOLO VENTA SE DUPLICARÍA.
                ,'TOTAL' NSE
                ,'TOTAL' TIPO_FAMILIA
                ,REGION
                ,'TOTAL' FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6
            
            UNION
            
            --TIENDA
                --MARCA
            SELECT
                'FORMATO_TIENDA' TABLA
                ,MARCA
                ,'TOTAL' NSE
                ,'TOTAL' TIPO_FAMILIA
                ,'TOTAL' REGION
                ,FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6
            
            UNION
            
                --TOTAL MARCA
            SELECT
                'FORMATO_TIENDA' TABLA
                ,'{proveedores}' MARCA --AUNQUE MARCA ES GLOBAL, NO OCUPAMOS IND_DUPLICADO YA QUE SE CUENTAN DISTINCTOS CLIENTES, NO SE DUPLICAN. SOLO VENTA SE DUPLICARÍA.
                ,'TOTAL' NSE
                ,'TOTAL' TIPO_FAMILIA
                ,'TOTAL' REGION
                ,FORMATO_TIENDA
                ,COUNT(DISTINCT CUSTOMER_CODE) CLIENTES
            FROM CHEDRAUI.VTA
            WHERE IND_MC = 1
            AND IND_MARCA = 1
            AND PERIODO = 'ACTUAL'
            GROUP BY 1,2,3,4,5,6
            )
            SELECT
                '{id}' ID_RADIOGRAFIA    
                ,*
            FROM __SEGMENTADO
            );

            DELETE CHEDRAUI.MON_RAD_SEGMENTADO WHERE ID_RADIOGRAFIA = '{id}';
            INSERT INTO CHEDRAUI.MON_RAD_SEGMENTADO SELECT * FROM #MON_RAD_SEGMENTADO UNION SELECT  '{id}' AS ID_RADIOGRAFIA, * FROM CHEDRAUI.MON_RAD_SEGMENTOS_CHEDRAUI;
        """

        query_rad_mix = f"""
            SELECT 1 AS ONE;
        """

        query_lis = [query_rad_desc, query_vta, query_rad_productos, query_rad_cat, query_rad_datos_producto, query_rad_marca, query_rad_funnel_clientes, query_rad_evolucion, query_rad_segmentado] #, query_rad_mix]

        return query_lis

    def validate_if_rad_exists(self, conn, inicio, termino, nombre):
        # Preguntar si las tablas de radiografia ya existen con el id y nombre ingresado
        id_rad, _, _ = self.__get_id_rad(conn, inicio, termino, nombre)
        df_res = conn.select(query=f"SELECT 1 AS RESULT FROM CHEDRAUI.MON_RAD_DESC WHERE UPPER(ID_RADIOGRAFIA) = '{id_rad}' LIMIT 1")
        return not df_res.empty

    def __get_id_rad(self, conn, inicio, termino, nombre):
        # Obtener el o los proveedores de los productos seleccionados. Si es más de 1 proveedor, concatenar con guión
        proveedores = conn.select(query=f'SELECT DISTINCT PROVEEDOR FROM #PRODUCTOS')['proveedor'].str.cat(sep='-')

        # Concatenar los dos ultimos digitos del año de inicio, 2 dígitos del mes de inicio, dos ultimos digitos del año de termino, 2 dígitos del mes de termino, los proveedores y el nombre
        id = f"{inicio[2:4]}{inicio[5:7]}_{termino[2:4]}{termino[5:7]}_{proveedores}_{nombre}".replace(' ', '_')
        return id.upper(), proveedores.upper(), nombre.upper()

    def create_tables_rad(self, conn, override=False):
        id_rad, proveedores, nombre = self.__get_id_rad(conn, self.inicio, self.termino, self.nombre)
        # Crear tablas de Radiografía
        query_lis = self.get_query_create_rad_tables(id=id_rad, proveedores=proveedores, nombre=nombre)
        
        # Mostrar una barra de progreso para la creación de las tablas con tqdm
        for query in tqdm(query_lis, desc='Creating Radiografia tables'):
            # Si override no se especifica, la tabla no existe, se crea
            if override is None:
                conn.execute(query=query)
            # Si override es True, se sobreescribe la tabla
            elif override:
                print('Overriding tables...')
                conn.execute(query=query)
            # Si override es False, se espera que la tabla exista, no se hace nada. Salir de la función
            # else:
            #     return
        
    def select_radiografias(self, conn):
        query = """
            SELECT DISTINCT
                PROVEEDOR
                ,NOMBRE
            FROM CHEDRAUI.MON_RAD_DESC
        """
        dic = conn.select(query).groupby('proveedor')['nombre'].apply(list).to_dict()
        keys = list(dic.keys())
        return dic, keys

